services:
  manager_study:
    container_name: wyolo_manager
    build:
      context: .
      dockerfile: app/Dockerfile
    image: wisrovi/train_service:manager_orchestrator_v1.0.0
    restart: unless-stopped
    env_file:
      - control_host.env
    # volumes:
    #   - ./app:/app/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ui:
    container_name: wyolo_ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    image: wisrovi/train_service:manager_ui_v2.0.0
    restart: always
    env_file:
      - control_host.env
    ports:
      - "23444:80"
    # volumes:
    #   - ./app:/app/app
    #   - ./UI:/app/UI
    depends_on:
      - manager_study

  # tester:
  #   build:
  #     context: .
  #     dockerfile: tests/Dockerfile
  #   image: wisrovi/train_service_manager_tester:v1.0.0
  #   container_name: wyolo_tester
  #   profiles: ["debug"]
  #   env_file:
  #     - control_host.env
  #   volumes:
  #     - ./app:/app/app
  #     - ./tests:/app/tests
  #   depends_on:
  #     - manager_study
