version: "3.3"
services:
  manager_study:
    build: ./manager
    image: wisrovi/train_service/manager/orchestrator:v1.0.0
    command: celery -A user_orchestrator worker -Q managers --concurrency=1 -P solo --loglevel=info
    network_mode: "host"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://192.168.1.137:23437/0}
    volumes:
      - ./manager:/app

  